[pytest]
pythonpath = .
testpaths = tests/unit
addopts = --tb=short

markers =
    slow: mark test as slow (deselect with '-m "not slow"')
    network: mark test as requiring network access (deselect with '-m "not network"')
    integration: mark test as an integration test (deselect with '-m "not integration"')
