[pytest]
pythonpath = .
testpaths = tests/unit tests/smoke
addopts = --tb=short -m "not network and not slow and not integration"

markers =
    slow: mark test as slow (deselect with '-m "not slow"')
    network: mark test as requiring network access (deselect with '-m "not network"')
    integration: mark test as an integration test (deselect with '-m "not integration"')
